name: Actions Ecosystem Slack Notifier
description: Send notifications to Slack.
author: The Actions Ecosystem Authors
inputs:
  slack_token:
    description: A Slack token.
    required: true
  message:
    description: A message for the channel. Supports Markdown format.
    required: true
  channel:
    description: A channel that will receives the message. e.g.) `develop`, `#develop`
    required: true
  username:
    description: The username who sends a message.
    required: false
    default: "GitHub Actions"
  color:
    description: The color of a message. The color names {black, red, green, yellow, blue, magenta, cyan, white} and color code (e.g., `#4CAF50`) are available. The default is no-color.
    required: false
  verbose:
    description: "Whether message contains GitHub context: repository, ref, workflow, event, action, number"
    required: false
    default: "false"
runs:
  using: node12
  main: dist/index.js
branding:
  icon: bell
  color: yellow
